site_name: EcoLogits
site_url: https://ecologits.ai
repo_name: genai-impact/ecologits
repo_url: https://github.com/genai-impact/ecologits


nav:
  - 'Getting Started': index.md


theme:
  name: material
#  logo: assets/logo.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate



watch:
  - docs


plugins:
  - search


markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

